FROM quay.io/fedora-ostree-desktops/kinoite:37

COPY images/foundation/etc /etc
COPY images/foundation/usr /usr

# Enable RPM Fusion and install it properly to avoid local override issues
RUN rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
rpm-ostree install rpmfusion-nonfree-release rpmfusion-free-release --uninstall=rpmfusion-free-release-$(rpm -E %fedora)-1.noarch --uninstall=rpmfusion-nonfree-release-$(rpm -E %fedora)-1.noarch

# Install mesa-freeworld for proper video decode in native firefox
RUN rpm-ostree override remove mesa-va-drivers --install=mesa-va-drivers-freeworld --install=mesa-vdpau-drivers-freeworld

# Install and enable System76 Scheduler (kylegospo COPR)
RUN wget https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-$(rpm -E %fedora)/kylegospo-system76-scheduler-fedora-$(rpm -E %fedora).repo -O /etc/yum.repos.d/_copr_kylegospo-system76-scheduler.repo && \
rpm-ostree install system76-scheduler && \
systemctl enable com.system76.Scheduler.service

# Install extra packages and finalize
RUN rpm-ostree install \
distrobox \
# ffmpeg \
# ffmpeg-libs \
# gstreamer1-plugin-openh264 \
# gstreamer1-plugins-bad-freeworld \
# gstreamer1-plugins-ugly \
# totem \
# libva-utils \
# NetworkManager-sstp \
langpacks-en \
duperemove && \
sed -i 's/#AutomaticUpdatePolicy.*/AutomaticUpdatePolicy=stage/' /etc/rpm-ostreed.conf && \
systemctl enable rpm-ostreed-automatic.timer && \
rpm-ostree cleanup -m && \
ostree container commit
