#!/bin/sh

if test -e "$HOME"/.config/sb-custom/foundation-done; then
    echo "Already ran"
    exit 0
fi

(
echo "# Waiting for Internet connection"
until /usr/bin/ping -q -c 1 flathub.org; do sleep 1; done
echo "00"

echo "# Removing Filtered Flathub Repository"
/usr/bin/flatpak remote-delete flathub --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Filtered Flathub Repo Failed"
        exit 1
fi
echo "3"

echo "# Enabling Flathub Repository"
/usr/bin/flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Adding Flathub Repo Failed"
        exit 1
fi
echo "5"

echo "# Removing Junk Flatpaks"
/usr/bin/flatpak uninstall --user --system --noninteractive org.gnome.Maps
/usr/bin/flatpak uninstall --user --system --noninteractive org.gnome.Contacts
/usr/bin/flatpak uninstall --user --system --noninteractive org.gnome.Characters
/usr/bin/flatpak uninstall --user --system --noninteractive org.gnome.Weather
/usr/bin/flatpak uninstall --user --system --noninteractive org.gnome.font-viewer
/usr/bin/flatpak uninstall --user --system --noninteractive org.gnome.Connections
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Junk Flatpaks Failed"
        exit 1
fi
echo "15"

echo "# Replacing Fedora Flatpaks with Flathub Ones"
/usr/bin/flatpak install --user --noninteractive org.gnome.Platform//43
/usr/bin/flatpak install --user --noninteractive --reinstall flathub $(flatpak list --app-runtime=org.fedoraproject.Platform --columns=application | tail -n +1 )
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Replacing Fedora Flatpaks Failed"
        exit 1
fi
echo "20"

echo "# Removing Fedora Flatpak Repository"
/usr/bin/flatpak remote-delete fedora --force ||:
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Removing Fedora Flatpak Repo Failed"
        exit 1
fi
echo "25"


echo "# Installing Gradience"
/usr/bin/flatpak install --user --noninteractive flathub com.github.GradienceTeam.Gradience
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Gradience Failed"
        exit 1
fi
echo "30"

echo "# Installing Extension Manager"
/usr/bin/flatpak install --user --noninteractive flathub com.mattjakeman.ExtensionManager
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Extension Manager Failed"
        exit 1
fi
echo "40"

echo "# Installing Discord"
/usr/bin/flatpak install --user --noninteractive flathub com.discordapp.Discord
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Discord Failed"
        exit 1
fi
echo "45"

echo "# Installing OpenRGB"
/usr/bin/flatpak install --user --noninteractive flathub org.openrgb.OpenRGB
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing OpenRGB Failed"
        exit 1
fi
echo "47"

echo "# Installing Steam"
/usr/bin/flatpak install --user --noninteractive flathub com.valvesoftware.Steam
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Steam Failed"
        exit 1
fi
echo "50"


echo "# Installing Steam Utilities"
/usr/bin/flatpak install --user --noninteractive flathub com.valvesoftware.Steam.CompatibilityTool.Proton-GE
/usr/bin/flatpak install --user --noninteractive org.freedesktop.Platform.VulkanLayer.MangoHud
/usr/bin/flatpak install --user --noninteractive org.freedesktop.Platform.VulkanLayer.vkBasalt
/usr/bin/flatpak install --user --noninteractive com.valvesoftware.Steam.Utility.gamescope
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Proton-GE Failed"
        exit 1
fi
echo "55"

echo "# Installing Protontricks"
/usr/bin/flatpak install --user --noninteractive flathub com.github.Matoking.protontricks
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Protontricks failed"
        exit 1
fi
echo "60"

echo "# Installing Lutris"
/usr/bin/flatpak install --user --noninteractive flathub net.lutris.Lutris
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Lutris Failed"
        exit 1
fi
echo "65"

echo "# Installing Heroic Games Launcher"
/usr/bin/flatpak install --user --noninteractive flathub com.heroicgameslauncher.hgl
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Heroic Failed"
        exit 1
fi
echo "68"

echo "# Installing LibreOffice"
/usr/bin/flatpak install --user --noninteractive flathub org.libreoffice.LibreOffice
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing LibreOffice Failed"
        exit 1
fi
echo "70"


echo "# Installing Protonup-QT"
/usr/bin/flatpak install --user --noninteractive flathub net.davidotek.pupgui2
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing ProtonUP-QT Failed"
        exit 1
fi
echo "75"

echo "# Installing Font Downloader"
/usr/bin/flatpak install --user --noninteractive flathub org.gustavoperedo.FontDownloader
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing FontDownloader Failed"
        exit 1
fi
echo "85"

echo "# Installing Flatseal"
/usr/bin/flatpak install --user --noninteractive flathub com.github.tchx84.Flatseal
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Flatseal Failed"
        exit 1
fi
echo "90"

echo "# Setting up Default Terminal Toolbox"
/usr/bin/distrobox-create --image fedora:37 --name Toolbox --yes &> /dev/null
/usr/bin/gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gsettings get org.gnome.Terminal.ProfilesList default | cut -d "'" -f 2)/ visible-name Default
/usr/bin/gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gsettings get org.gnome.Terminal.ProfilesList default | cut -d "'" -f 2)/ use-custom-command true
/usr/bin/gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gsettings get org.gnome.Terminal.ProfilesList default | cut -d "'" -f 2)/ custom-command "distrobox enter Toolbox"
echo "95"

echo "# Setting up theme"
/usr/bin/gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
/usr/bin/gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
/usr/bin/gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Failed to Configure Theme"
        exit 1
fi
echo "96"

echo "# Disabling mouse acceleration"
/usr/bin/gsettings set org.gnome.desktop.peripherals.mouse accel-profile flat
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Failed to disable mouse acceleration"
        exit 1
fi
echo "97"

echo "# Installing Celluloid Media Player"
/usr/bin/flatpak install --user --noninteractive flathub io.github.celluloid_player.Celluloid
if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Installing Celluloid Failed"
        exit 1
fi
echo "100"

echo "# Reticulating Final Splines"
mkdir -p "$HOME"/.config/sb-custom/
touch "$HOME"/.config/sb-custom/foundation-done

) | 
     
   zenity --progress --title="Foundation Image Desktop Firstboot" --percentage=0 --auto-close --no-cancel --width=300

if [ "$?" != 0 ] ; then
        zenity --error \
          --text="Firstboot Configuration Error"
fi
